
version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - npm run build
      - yarn run build
artifacts:
  files:
    - 'build/* '
    - 'appspec.yml'
